"""empty message

Revision ID: 6c803c8fbb0c
Revises: 
Create Date: 2020-03-14 22:03:48.638601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c803c8fbb0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RemoteClient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('client_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RemoteClient_client_token'), 'RemoteClient', ['client_token'], unique=False)
    op.create_index(op.f('ix_RemoteClient_username'), 'RemoteClient', ['username'], unique=True)
    op.create_table('Email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_email_address', sa.String(), nullable=True),
    sa.Column('message_content', sa.String(), nullable=True),
    sa.Column('remote_client_id', sa.Integer(), nullable=True),
    sa.Column('transaction_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['remote_client_id'], ['RemoteClient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Email_contact_email_address'), 'Email', ['contact_email_address'], unique=False)
    op.create_table('SMS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('message_content', sa.String(), nullable=True),
    sa.Column('remote_client_id', sa.Integer(), nullable=True),
    sa.Column('transaction_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['remote_client_id'], ['RemoteClient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SMS_contact_number'), 'SMS', ['contact_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SMS_contact_number'), table_name='SMS')
    op.drop_table('SMS')
    op.drop_index(op.f('ix_Email_contact_email_address'), table_name='Email')
    op.drop_table('Email')
    op.drop_index(op.f('ix_RemoteClient_username'), table_name='RemoteClient')
    op.drop_index(op.f('ix_RemoteClient_client_token'), table_name='RemoteClient')
    op.drop_table('RemoteClient')
    # ### end Alembic commands ###
